// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqUNC1h2O3pseeDYdRjfYCkSfGBwbnVis',
    appId: '1:749213753046:web:b4bd0646f11afb8963b377',
    messagingSenderId: '749213753046',
    projectId: 'tabuk-ce16e',
    authDomain: 'tabuk-ce16e.firebaseapp.com',
    storageBucket: 'tabuk-ce16e.appspot.com',
    measurementId: 'G-52GRD9NJDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEeIzEOXmrCFNYt7f2QHM43lcq8fZtTsE',
    appId: '1:749213753046:android:46dc2fafe60501ee63b377',
    messagingSenderId: '749213753046',
    projectId: 'tabuk-ce16e',
    storageBucket: 'tabuk-ce16e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATZftO3SXnK0-sWqq3-5Ew5eHcUvGAhL8',
    appId: '1:749213753046:ios:cbc4d65e4b10a40a63b377',
    messagingSenderId: '749213753046',
    projectId: 'tabuk-ce16e',
    storageBucket: 'tabuk-ce16e.firebasestorage.app',
    androidClientId:
        '749213753046-493nqc2qlkphluopef0chsq140rbp64g.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATZftO3SXnK0-sWqq3-5Ew5eHcUvGAhL8',
    appId: '1:749213753046:ios:cbc4d65e4b10a40a63b377',
    messagingSenderId: '749213753046',
    projectId: 'tabuk-ce16e',
    storageBucket: 'tabuk-ce16e.firebasestorage.app',
    androidClientId:
        '749213753046-493nqc2qlkphluopef0chsq140rbp64g.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqUNC1h2O3pseeDYdRjfYCkSfGBwbnVis',
    appId: '1:749213753046:web:d57034830053a7d563b377',
    messagingSenderId: '749213753046',
    projectId: 'tabuk-ce16e',
    authDomain: 'tabuk-ce16e.firebaseapp.com',
    storageBucket: 'tabuk-ce16e.appspot.com',
    measurementId: 'G-8GPLK0YKEW',
  );
}
