plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
    id("com.google.gms.google-services")
}

dependencies {
    // Import the Firebase BoM
    implementation(platform("com.google.firebase:firebase-bom:33.14.0"))
    // Add the dependency for the Firebase Authentication library
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation("com.google.firebase:firebase-auth")
    
    // Also add the dependency for the Google Play services library and specify its version
    implementation("com.google.android.gms:play-services-auth:21.3.0")
    
    // Add multidex support
    implementation("androidx.multidex:multidex:2.0.1")
}

android {
    namespace = "com.example.capstone_app"
    compileSdk = 36  // Updated to match plugin requirements
    ndkVersion = "27.0.12077973"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        buildConfig = true  // Enable BuildConfig feature
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.example.capstone_app"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = 35  // Updated to match plugin requirements

        versionCode = 1  // Fixed version instead of flutter.versionCode
        versionName = "1.0"  // Fixed version instead of flutter.versionName
        // Enable multidex for large apps
        multiDexEnabled = true
        
        // Add manifest placeholders for API keys
        // Note: This is overridden by buildTypes, but kept for consistency
        manifestPlaceholders["GOOGLE_MAPS_API_KEY"] = project.findProperty("GOOGLE_MAPS_API_KEY")
            ?: System.getenv("GOOGLE_MAPS_API_KEY")
            ?: ""
    }

    // Signing configurations for release builds (preserved for future use)
    signingConfigs {
        // Release signing configuration - preserved but inactive during debug development
        // To activate for release builds, uncomment the code below and configure key.properties
        /*
        create("release") {
            val keystorePropertiesFile = rootProject.file("key.properties")
            val keystoreProperties = java.util.Properties()
            if (keystorePropertiesFile.exists()) {
                keystoreProperties.load(java.io.FileInputStream(keystorePropertiesFile))
                storeFile = file(keystoreProperties["storeFile"] as String)
                storePassword = keystoreProperties["storePassword"] as String
                keyAlias = keystoreProperties["keyAlias"] as String
                keyPassword = keystoreProperties["keyPassword"] as String
            }
        }
        */
    }

    buildTypes {
        // DEBUG BUILD TYPE - Optimized for development and testing
        // This configuration ensures smooth debugging without release security restrictions
        debug {
            // EXPLICITLY DISABLED: Minification is OFF for debug builds
            // This ensures no code obfuscation, making debugging easier
            isMinifyEnabled = false
            
            // EXPLICITLY DISABLED: ProGuard/R8 rules are NOT applied
            // Your proguard-rules.pro file is preserved but inactive during debug builds
            
            // Uses default debug signing key (automatically generated by Android)
            // This means your debug SHA-1 fingerprint will work with your Google Maps API key
            
            // API Key Configuration:
            // 1. First tries to get from --dart-define=ANDROID_GOOGLE_MAPS_API_KEY=...
            // 2. Falls back to environment variable GOOGLE_MAPS_API_KEY
            // 3. Final fallback: Hardcoded dev key (matches debug SHA-1)
            val googleMapsKey = project.findProperty("ANDROID_GOOGLE_MAPS_API_KEY")
                ?: System.getenv("ANDROID_GOOGLE_MAPS_API_KEY")
                ?: project.findProperty("GOOGLE_MAPS_API_KEY")
                ?: System.getenv("GOOGLE_MAPS_API_KEY")
                ?: "AIzaSyDEeIzEOXmrCFNYt7f2QHM43lcq8fZtTsE" // Android key (auto created by Firebase)

            buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"$googleMapsKey\"")
            manifestPlaceholders["GOOGLE_MAPS_API_KEY"] = googleMapsKey
            
            // Debug-specific settings (OPTIONAL - commented to avoid package name conflicts)
            // Uncomment these if you want to install debug and release builds side-by-side
            // NOTE: If uncommented, ensure your Google Maps API key also allows the .debug package
            // applicationIdSuffix = ".debug"  // Allows installing debug and release side-by-side
            // versionNameSuffix = "-debug"   // Shows debug version in app info
        }
        
        // RELEASE BUILD TYPE - All security features preserved and ready for production
        // This configuration remains intact but inactive during debug development
        release {
            // ENABLED: Minification is ON for release builds (inactive during debug)
            // This reduces APK size by removing unused code
            isMinifyEnabled = true
            
            // ENABLED: ProGuard/R8 rules ARE applied in release builds
            // Your proguard-rules.pro file will be used when building release APK
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            
            // RELEASE SIGNING CONFIGURATION - Preserved but currently using debug for testing
            // To activate release signing for production:
            // 1. Uncomment the signingConfigs block above
            // 2. Configure android/key.properties with your release keystore details
            // 3. Change the line below to: signingConfig = signingConfigs.getByName("release")
            signingConfig = signingConfigs.getByName("debug")  // TEMPORARY: Using debug for testing
            
            // API Key Configuration for Release:
            // Must be provided via --dart-define or environment variable
            // No fallback key - fails safely if not provided
            val googleMapsKey = project.findProperty("ANDROID_GOOGLE_MAPS_API_KEY")
                ?: System.getenv("ANDROID_GOOGLE_MAPS_API_KEY")
                ?: project.findProperty("GOOGLE_MAPS_API_KEY")
                ?: System.getenv("GOOGLE_MAPS_API_KEY")
                ?: ""  // Empty string - requires explicit API key for release builds

            buildConfigField("String", "GOOGLE_MAPS_API_KEY", "\"$googleMapsKey\"")
            manifestPlaceholders["GOOGLE_MAPS_API_KEY"] = googleMapsKey
            
            // Release optimizations (inactive during debug)
            isShrinkResources = true  // Remove unused resources in release builds
        }
    }
}

flutter {
    source = "../.."
}
